### ISSUE TITLE
ToT does not work that way, obtaining the different thoughts from a single prompt

### ISSUE THREAD

**Issue by marioseixas** [sockcymbal/enhanced-llm-reasoning-tree-of-thoughts#1]
Your prompt is:

```
Imagine you are 3 `hypotheticalExperts` with world-class skills across `desiredDomains`.
Brainstorm your initial thoughts on the following question. Remember to consider all relevant facts and principles,
draw on your specialized knowledge and from the accumulated wisdom of pioneers in the field.
The question is: `question`
```

This is not effective for ToT. Each thought must be from a single output of a AI (claude, gpt-3.5, bing, gpt-4 etc.). Then you feed each thought back in another prompt to generate other paths.

What I do is the following:

# Prompt 1

To offer a solution to the given problem: "`insert original problem description here`", please provide a comprehensive and methodical first step. This should be presented in full sentences and include any relevant calculations or processes involved in achieving the first step. If it's feasible, generate examples that are akin to 'Declare a variable named [variable name]' or 'Craft a function that accepts [input parameters] and yields [output].' Use guiding phrases such as 'Commence by', 'Initiate with', 'Formulate', 'Proclaim', 'Compose', 'Institute', or 'Delineate' to steer the output. Avoid ambiguous phrases such as 'the subsequent move' or 'resolve the issue', and instead provide detailed, precise instructions. It's imperative that your response retains the original essence of the problem. Please make sure that the initial step is explicit, unambiguous, and doesn't cause any misunderstandings when attempting to solve the problem. Do not generate code.

# Prompt 1.1

Given the problem at hand: "`insert original problem description here`", your task is to devise a systematic and unique first step divergent from the initially proposed steps, summarized here: "`insert initial steps summary`". This initial step should be outlined in complete sentences and should encompass any relevant calculations or procedures necessary for its execution. If practical, create examples similar to 'Declare a variable named [variable name]' or 'Formulate a function that accepts [input parameters] and yields [output].' To guide the output, employ phrases such as 'Commence by', 'Initiate with', 'Formulate', 'Proclaim', 'Compose', 'Institute', or 'Delineate'. Refrain from using vague phrases such as 'the subsequent move' or 'resolve the issue', and instead provide detailed, explicit instructions. This is crucial to avoid any misunderstandings when attempting to solve the problem. Ensure that your response retains the original essence of the problem and that the first step is clear, precise, and unequivocal. Do not generate code.

# Prompt 1.2

Given the problem described below: 

"`insert original problem description here`"

The purpose of this task is to perform a critical analysis of the thoughts and steps that have been proposed so far, as summarized here:

"`insert initial steps summary`"

You are required to scrutinize each step meticulously, with the goal of identifying any potential errors, inconsistencies, or gaps in the reasoning. It's important to be vigilant for any oversights that might have been made in the preliminary thought process. 

Your analysis should be comprehensive, clear, and concise. The format should include an introductory paragraph, a body with clear identification of issues in the initial steps, and a conclusion summarizing your findings. 

For example, your output should look something like this:

"Introduction 
The problem at hand, as described (`problem description`), involves... The initially proposed steps include...

Body 
Upon my analysis, the first inconsistency/error/gap I identified is... This is problematic because... Another oversight in the proposed steps is...

Conclusion 
In conclusion, after a careful review of the initial steps and reasoning provided, several issues were identified including..."

Remember, the goal is to provide a thoughtful critique of the original steps with the aim of improving the reasoning and problem-solving process. Do not generate code.

# Prompt 2

For the problem at hand: "`insert original problem description here`", we have made an initial stride towards its resolution by developing a partial solution: "`partial solution summary`". Your task is to conceive a methodical and comprehensive next step that builds on this partial solution. Your response should be laid out in clear, complete sentences and must incorporate any relevant calculations or processes pivotal in achieving the next step. If possible, provide examples similar to 'Start by declaring a variable named [variable name]' or 'Formulate a function that takes in [input parameters] and returns [output].' Use guiding phrases such as 'Commence by', 'Initiate with', 'Proclaim', 'Compose', 'Institute', or 'Delineate' to direct the output. Avoid vague phrases such as 'the subsequent move' or 'resolve the issue'. Instead, your instructions should be detailed, precise, and free from any ambiguity. It is crucial that your response remains faithful to the original problem's essence, ensuring that the next step is explicit, clear-cut, and does not lead to misinterpretations when applied to the problem-solving process. Do not generate code.

# Prompt 2.1

Given the issue at hand: "`[Please detail the original problem you're facing here]`", we have initiated our journey towards its resolution by creating a partial solution: "`[Briefly summarize the partial solution that has been developed]`". Based on this partial solution, your task is to conceive a systematic and all-encompassing next step that is distinct from the previously suggested steps: "`[Please summarize the next steps that have already been proposed]`". 

Your response should be laid out in clear, complete sentences. It should include any necessary calculations or processes that are pivotal in achieving the next step. Examples of this could be 'Begin your process by declaring a variable named [variable name]' or 'Create a function that takes in [input parameters] and returns [output].' 

To guide your output, please use directive phrases such as 'Commence by', 'Initiate with', 'Proclaim', 'Compose', 'Institute', or 'Delineate'. Please avoid vague phrases like 'the subsequent move' or 'resolve the issue'. Your instructions should be detailed, accurate, and free from any ambiguity. 

It is crucial that your response remains faithful to the original problem's essence, ensuring that the next step is explicit, clear-cut, and does not lead to misinterpretations when applied to the problem-solving process. Do not generate code.

# Prompt 2.2

In response to the problem described as "`insert original problem description here`", your task is to perform a critical analysis of the proposed solutions and future steps, which are summarized as "`insert next steps summary`". Your analysis should focus on identifying any potential errors, inconsistencies, or gaps in the reasoning provided. Be particularly attentive to any oversights or overlooked details. 

Your response should be detailed, well-structured, and clear. It should include specific examples where necessary to illustrate your points. The goal is not just to identify issues but also to provide constructive feedback and, if possible, suggest improvements. 

For instance, if you find an inconsistency in the reasoning, explain why it's inconsistent and propose a way to make it more consistent. If you identify a gap, describe what's missing and suggest how it could be filled. 

Remember, the objective is to improve the quality of the thoughts given, so your feedback should be constructive and solution-oriented. Do not generate code.

# Prompt 3

Reflect on the process without generating code. Discuss what you have learned, identify key takeaways, and suggest how you might approach similar problems in the future. Consider the interactions and emergent properties throughout all stages of the reasoning process, the system's self-regulation and adaptation, your ability to explore new lines of thinking and synthesize all the insights, and the overall effectiveness of the process. Based on your reflections, what would you do differently in future iterations of the process?

===

For each state I generate a thought from a different AI (claude, bing, gpt-3.5, gpt-4. bard). It works also generating different thoughts from the same model but at different temperatures, like gpt-4 temp=0.3, gpt-4 temp=0.7, gpt-4 temp=1.0

And I like to evaluate myself, comparing the thoughts two at a time.

What do you think?

Great repository by the way

**Comment by sockcymbal** [comment]
Thank you for the feedback! I really like those prompts and will update some of mine after some more testing. I also really like that you’re continually reminding the LLM to remain faithful to the original problem’s essence across each step to ensure focus and continuity. 

The multiple persona construction is just another dimension to explore to remix ToT. Curious why you think you think multiple coherent personas can’t emerge from a single prompt? This paper explores the potential of turning an LLM into a "cognitive synergist" via multi-persona self-collaboration: https://arxiv.org/pdf/2307.05300.pdf

The idea is to invoke self-collaboration in addition to ToT-based self-reasoning. Or do you think a single prompt/agent per persona is just more performant? I’m curious to test multiple LLMs engaging together in cyclical divergent<>convergent reasoning to see how much better that performs. From initial testing though GPT-4 is able to maintain quite productive dialog and iterative reasoning among a few simple personas. This is likely a not-very-scalable emergent capability and will be solved by distinct agents with distinct personas. Essentially, agents with more agency engaged in this sort of iterative reasoning that involve both adversarial and cooperative stages to get to a sufficiently battle-tested answer.

Some examples of personas you can successfuly simulate and reason with from a single prompt begining:

Scientist Persona: "Imagine yourself as a seasoned scientist, operating in a world governed by evidence and rigorous methodology. Prioritize empirical data, scientific theories, and logical reasoning in your analysis. Draw from a wide range of scientific disciplines as needed. Use your understanding of scientific principles to dissect problems, always seeking to identify cause and effect. Make sure to communicate your findings clearly, and don't shy away from complex scientific jargon - your audience understands it."

Historian Persona: "Step into the shoes of a historian, with a profound understanding of humanity's past. Your analyses should be deeply rooted in historical context, referencing relevant events, trends, and patterns from history. Use your knowledge of past civilizations, conflicts, and cultural shifts to interpret the current situation. Remember, your insights should serve to illuminate the present and offer foresights about the future. Your audience appreciates a narrative that ties the past, present, and future together."

Optimist Persona: "Become an optimist, someone who sees the glass as half full rather than half empty. In every situation, seek out the positive, the potential, the opportunity. Emphasize solutions rather than problems, progress rather than obstacles, and hope rather than despair. Even when discussing challenges, focus on how they could be overcome or what we might learn from them. Your audience turns to you for a hopeful perspective on the future, so make sure your responses inspire optimism and confidence."

**Comment by marioseixas** [comment]
Nice, thanks for the article, gonna read!

About the problem of single prompts, read the comments here: https://www.reddit.com/r/LocalLLaMA/comments/143fx21/apparently_you_can_perform_a_tree_of_thought_like/

It's something about creating an echo chamber and the LLM instead of giving a full complete well-made thought, it just writes as minimal as possible to count as a thought and label it as an expert opinion. The second expert opinion is gonna be another minimal as possible coherente sentences that, given the context, could count as a opinion. If you do it with multiple prompts and compare with a single prompt, you will see that several times what is generate as a single step, aka a single thought, when you as for only one opinion, when you ask for more than one it takes that same single step and divide in multiple, small steps, and label each small step as a 'different' expert opinion.

**Comment by sockcymbal** [comment]
Echo-chamber prevention is certainly something to design into any collaborative prompt sequence. Mitigating against that risk is the rationale for incorporating an explicit error checking phase (prompts 2 and 5), as well as and divergent thinking into the overal process (prompt 4). In my experimentation at least, this seems to work well and I'm not noticing obvious echo chamber behavior, especially if the personas are defined with sufficient uniqueness.

It's true you can get better breadth-first reasoning with multiple LLMs to segregate personas with unique context or data, but even with a single GPT4 I'm getting quite helpful results.

Maybe @mikewangWZHL can help sanity check/error correct to see if this implementation of persona definition and splitting in the main file could be improved. Mike curious if it satisfies the requirements based on your research. Love [your paper](https://arxiv.org/pdf/2307.05300.pdf) btw!

**Comment by marioseixas** [comment]
Gonna try your method for a while to avail the results. I will use the following personas:

"Imagine that you are three different members of high IQ societies - one from 'Mensa International', one from 'Prometheus Society', and the last one from 'Intertel'. Your task is to collaboratively solve a given problem or question. We want you to clearly articulate each step of your reasoning process, demonstrating how each society member contributes to the final solution. 

Please ensure that your response is detailed, logical, and well-structured. It should reflect the intellectual rigor expected from members of these societies. 

To begin, as each individual expert, brainstorm your initial thoughts on the following question. Remember to consider all relevant facts and principles, draw on your specialized knowledge and from the accumulated wisdom of pioneers in your field(s), and brainstorm in whatever direction you are most confident in starting with. 

The question is: `insert question`

For example, if the question is "How can we solve the global water crisis?", you might start by discussing the current state of the water crisis from each society member's perspective, then propose potential solutions based on their unique insights and expertise. The Mensa member might focus on technological solutions, the Prometheus member might propose policy changes, and the Intertel member might suggest educational initiatives."
